package com.openclassrooms.magicgithub.api;

import com.openclassrooms.magicgithub.model.User;

import java.util.List;
import java.util.Random;

import static com.openclassrooms.magicgithub.api.FakeApiServiceGenerator.FAKE_USERS_RANDOM;
import static com.openclassrooms.magicgithub.api.FakeApiServiceGenerator.generateUsers;

public class FakeApiService implements ApiService {

    private List<User> users = generateUsers();

    /**
     * Return a list of {@link User}
     * Those users must be generated by {@link FakeApiServiceGenerator}
     */
    @Override
    public List<User> getUsers() {
        // TODO: A modifier
        return users;
    }

    /**
     * Generate a random {@link User} and add it {@link FakeApiService#users} list.
     * This user must be get from the {@link FakeApiServiceGenerator#FAKE_USERS_RANDOM} list.
     */
    @Override
    public void generateRandomUser() {
        // TODO: A modifier

        double randomIndex = Math.random() * FAKE_USERS_RANDOM.size();
        User user = FAKE_USERS_RANDOM.get((int) randomIndex);

        //int randomIndex = new Random().nextInt(FAKE_USERS_RANDOM.size());
        //User user = FAKE_USERS_RANDOM.get(randomIndex);
        users.add(user);
    }

    /**
     * Delete a {@link User} from the {@link FakeApiService#users} list.
     */
    @Override
    public void deleteUser(User user) {
        // TODO: A modifier

        //users.remove(user);

        int indexEnd = users.size() - 1;
        for (int index = 0; index <= indexEnd; index++) {
            if (user == users.get(index)) {
                users.remove(index);
                break;
            }
        }

    }
}
